[2025-10-08T19:59:22.773+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_api_to_postgres.save_data_to_postgres manual__2025-10-08T19:59:16.372151+00:00 [queued]>
[2025-10-08T19:59:22.795+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_api_to_postgres.save_data_to_postgres manual__2025-10-08T19:59:16.372151+00:00 [queued]>
[2025-10-08T19:59:22.796+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-10-08T19:59:22.832+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): save_data_to_postgres> on 2025-10-08 19:59:16.372151+00:00
[2025-10-08T19:59:22.851+0000] {standard_task_runner.py:57} INFO - Started process 2952 to run task
[2025-10-08T19:59:22.859+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '04_api_to_postgres', 'save_data_to_postgres', 'manual__2025-10-08T19:59:16.372151+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/04_example.py', '--cfg-path', '/tmp/tmp0fkx1ix4']
[2025-10-08T19:59:22.864+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask save_data_to_postgres
[2025-10-08T19:59:22.997+0000] {task_command.py:410} INFO - Running <TaskInstance: 04_api_to_postgres.save_data_to_postgres manual__2025-10-08T19:59:16.372151+00:00 [running]> on host a4407e4abc2c
[2025-10-08T19:59:23.160+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='bryan@gmail.com' AIRFLOW_CTX_DAG_OWNER='andrei' AIRFLOW_CTX_DAG_ID='04_api_to_postgres' AIRFLOW_CTX_TASK_ID='save_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T19:59:16.372151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-08T19:59:16.372151+00:00'
[2025-10-08T19:59:23.205+0000] {base.py:73} INFO - Using connection ID 'postgres_datapath' for task execution.
[2025-10-08T19:59:23.231+0000] {sql.py:375} INFO - Running statement: INSERT INTO users (name,username,email) VALUES ('Leanne Graham','Bret','Sincere@april.biz');, parameters: None
[2025-10-08T19:59:23.240+0000] {sql.py:384} INFO - Rows affected: 1
[2025-10-08T19:59:23.247+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-08T19:59:23.268+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=04_api_to_postgres, task_id=save_data_to_postgres, execution_date=20251008T195916, start_date=20251008T195922, end_date=20251008T195923
[2025-10-08T19:59:23.314+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-10-08T19:59:23.348+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
