[2025-10-16T19:39:33.854+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_api_to_postgres.get_data_from_api 10 [queued]>
[2025-10-16T19:39:33.889+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_api_to_postgres.get_data_from_api 10 [queued]>
[2025-10-16T19:39:33.890+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-10-16T19:39:33.940+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): get_data_from_api> on 2025-10-16 19:39:20+00:00
[2025-10-16T19:39:33.971+0000] {standard_task_runner.py:57} INFO - Started process 329 to run task
[2025-10-16T19:39:33.987+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '04_api_to_postgres', 'get_data_from_api', '10', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/04_example.py', '--cfg-path', '/tmp/tmpk9flocpw']
[2025-10-16T19:39:33.998+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask get_data_from_api
[2025-10-16T19:39:34.246+0000] {task_command.py:410} INFO - Running <TaskInstance: 04_api_to_postgres.get_data_from_api 10 [running]> on host 2cdd767518d4
[2025-10-16T19:39:34.549+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='bryan@gmail.com' AIRFLOW_CTX_DAG_OWNER='andrei' AIRFLOW_CTX_DAG_ID='04_api_to_postgres' AIRFLOW_CTX_TASK_ID='get_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T19:39:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='10'
[2025-10-16T19:39:34.980+0000] {logging_mixin.py:149} INFO - {'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz'}
[2025-10-16T19:39:34.983+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-16T19:39:35.014+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=04_api_to_postgres, task_id=get_data_from_api, execution_date=20251016T193920, start_date=20251016T193933, end_date=20251016T193935
[2025-10-16T19:39:35.080+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-10-16T19:39:35.138+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
